### ISSUE TITLE
Переименовать публичные методы

### ISSUE THREAD

**Issue by petrgrishin** [DsXack/container#3]

**Comment by DsXack** [comment]
Требуется список требуемых публичных методов с описанием их логики

**Comment by DsXack** [comment]
Ссылки для раздумий:
http://container.thephpleague.com/
http://laravel.com/docs/5.0/container
http://symfony.com/doc/current/components/dependency_injection/introduction.html
http://php-di.org/
http://pimple.sensiolabs.org/

**Comment by petrgrishin** [comment]
Текущие название | Новое название
---|---
make | get

**Comment by DsXack** [comment]
Текущие название | Описание | Аргументы
---|---|---
factory | устанавливаем фабрику для сервиса по сути использует bind | имя сервиса, фабрика
sharedFactory | устанавливаем фабрику для сервиса, который будет синглтон по сути использует bind (bindShared) | имя сервиса, фабрика
alias | устанавливаем алиас для сервиса | имя сервиса, алиас
bind | вспомогательный метод для bindShared, alias, factory, sharedFactory, позволяет устанавливать для сервиса фабрику или алиас | имя сервиса, фабрика или алиас, признак того, что сервис синглтон
bindShared | вспомогательный метод для sharedFactory, **думаю нужно его удалить** | имя сервиса, фабрика или алиас
set | установка синглтон инстанса для сервиса | имя сервиса, инстанс сервиса
get | получение инстанса сервиса | имя сервиса, параметры. **Нужно будет подумать о параметрах  - нужно ли учитывать то, что могут быть переданы разные параметры для сервиса-синглтона и как это обрабатывать**
isAlias | проверка на то, что сервис является алиасом на другой сервис | имя сервиса
getConcrete | получение имени сервиса по его алиасу или фабрику сервиса | имя сервиса
getFactory | получение фабрики сервиса по имени сервиса или имени его алиаса | имя сервиса или имя алиаса сервиса
isShared | является ли сервис синглтоном | имя сервиса
build | вызов объекта-билдера инстанса с указанием определенных зависимостей | имя сервиса
when | вызов объекта-билдера, который настраивает зависимости для сервиса | имя сервиса
global | метод, который позволяет обратиться к глобальному контейнеру, для его конфигурации

**Comment by petrgrishin** [comment]
Текущие название | Описание | Аргументы | Новое название
---|---|---|---
factory | устанавливаем фабрику для сервиса по сути использует bind | имя сервиса, фабрика | 
sharedFactory | устанавливаем фабрику для сервиса, который будет синглтон по сути использует bind (bindShared) | имя сервиса, фабрика | set
alias | устанавливаем алиас для сервиса | имя сервиса, алиас | bind
bind | вспомогательный метод для bindShared, alias, factory, sharedFactory, позволяет устанавливать для сервиса фабрику или алиас | имя сервиса, фабрика или алиас, признак того, что сервис синглтон |
bindShared | вспомогательный метод для sharedFactory, **думаю нужно его удалить** | имя сервиса, фабрика или алиас |
set | установка синглтон инстанса для сервиса | имя сервиса, инстанс сервиса | protect
get | получение инстанса сервиса | имя сервиса, параметры. **Нужно будет подумать о параметрах - нужно ли учитывать то, что могут быть переданы разные параметры для сервиса-синглтона и как это обрабатывать** |
isAlias | проверка на то, что сервис является алиасом на другой сервис | имя сервиса |
getConcrete | получение имени сервиса по его алиасу или фабрику сервиса | имя сервиса |
getFactory | получение фабрики сервиса по имени сервиса или имени его алиаса | имя сервиса или имя алиаса сервиса |
isShared | является ли сервис синглтоном | имя сервиса |
build | вызов объекта-билдера инстанса с указанием определенных зависимостей | имя сервиса |
when | вызов объекта-билдера, который настраивает зависимости для сервиса | имя сервиса |
global | метод, который позволяет обратиться к глобальному контейнеру, для его конфигурации |

**Comment by DsXack** [comment]
В данный момент созданы обращения #6 и #7. Дальнейшее обсуждение будет проходить в них
