### ISSUE TITLE
Предложение об именовании публичных методов №2

### ISSUE THREAD

**Issue by dsxack** [dsxack/container#7]
| Имя | Описание |
| --- | --- |
| factory | установка фабрики для сервиса |
| set | установка фабрики для общего (singleton) сервиса |
| bind | установка алиаса для сервиса |
| protect | установка сервиса |
| get | получение сервиса |
| when | вызов билдера настроек зависимостей для сервиса |
| build | вызов билдера для сервиса |
| global | получение глобального контейнера для дальнейшего взаимодействия с ним |

**Comment by petrgrishin** [comment]
Возможные примеры использования интерфейса

```coffee
container = new Container

container.set "notification", NotificationFactory
notification = container.get "notification"

container.factory "button", ButtonWidgetFactory
sendButton = container.get "button"
resetButton = container.get "button"
```

**Comment by dsxack** [comment]
Выполнено

**Comment by dsxack** [comment]
#6
